apiVersion: v1
kind: Service
metadata:
  name: kaf1
  lables:
    name: kafka
spec:
  type: LoadBalancer
  ports:
    - name: port-9092
      port: 9092
      protocol: TCP
  selector:
    app: kafka1
