apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafkaApp
spec:
  type: LoadBalancer
  ports:
    - name: port-9092
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: port-2181
      port: 2181
      targetPort: 2181
  selector:
    app: kafkaApp
