apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    app: kafka1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      containers:
      - name: kafka1
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "ac1d42bec632e4e1e9f5457fdeb01650-1717548211.us-east-2.elb.amazonaws.com"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
