apiVersion: v1
kind: Service
metadata:
  name: kafka
  lables:
    app: kafkaApp
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  - port: 2181
    targetPort: 2181
  selector:
    app: kafkaApp
  type: LoadBalancer
