--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: kafkaApp
  name: kafka
spec: 
  ports: 
    - 
      name: port-9092
      port: 9092
      protocol: TCP
      targetPort: 9092
    - 
      name: port-2181
      port: 2181
      targetPort: 2181
  selector: 
    app: kafkaApp
  type: LoadBalancer
